# Generated by Django 6.0 on 2025-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_add_group_and_teamgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(blank=True, help_text='Optional matchday/round number.', null=True),
        ),
    ]
