# Generated by Django 6.0 on 2025-12-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_match_matchday'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='awarded',
            field=models.BooleanField(default=False, help_text='True if match was awarded by protest or walkover.'),
        ),
        migrations.AddField(
            model_name='match',
            name='awarded_at',
            field=models.DateTimeField(blank=True, help_text='When the award was applied.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='awarded_by',
            field=models.CharField(blank=True, help_text='Admin username who applied the award.', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='awarded_reason',
            field=models.CharField(blank=True, choices=[('protest', 'Protest'), ('walkover', 'Walkover')], max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='awarded_to',
            field=models.ForeignKey(blank=True, help_text='Team awarded the win.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='league.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='original_away_score',
            field=models.IntegerField(blank=True, help_text='Backup of original away score before award.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='original_home_score',
            field=models.IntegerField(blank=True, help_text='Backup of original home score before award.', null=True),
        ),
    ]
