# Generated by Django 6.0 on 2025-12-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_match_awarded_match_awarded_at_match_awarded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalty_away',
            field=models.IntegerField(blank=True, help_text='Away team penalty score if decided on penalties', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_home',
            field=models.IntegerField(blank=True, help_text='Home team penalty score if decided on penalties', null=True),
        ),
    ]
