# Generated by Django 6.0 on 2025-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_match_penalty_away_match_penalty_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='archived',
            field=models.BooleanField(default=False, help_text="Mark placeholder or retired teams as archived so they don't appear in active lists"),
        ),
    ]
