# Generated by Django 6.0 on 2025-12-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_team_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='void',
            field=models.BooleanField(default=False, help_text='True if match was voided (e.g., both teams did not participate)'),
        ),
    ]
