# Generated by Django 6.0 on 2025-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_userrole_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_time_minutes',
            field=models.IntegerField(blank=True, help_text='Extra minutes applied when manually finished', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='manual_finished_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when match was manually marked finished', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='manual_finished_by',
            field=models.CharField(blank=True, help_text='User who manually marked finished', max_length=150),
        ),
    ]
