# Generated by Django 6.0 on 2025-12-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_match_extra_time_minutes_match_manual_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='actual_start',
            field=models.DateTimeField(blank=True, help_text='When the match actually started (can differ from scheduled match_date)', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_duration_minutes',
            field=models.IntegerField(default=150, help_text='Duration in minutes used to compute live window (default 150)'),
        ),
    ]
