# Generated by ChatGPT - add subtitle to News
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_match_actual_start_match_match_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=250, blank=True),
        ),
    ]
