# Generated by ChatGPT - add author to News
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_news_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=120, blank=True, help_text='Name of the person who posted this news'),
        ),
    ]
